consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  OpendbHackTransfer:
    description: OpendbHackTransfer media type (default view)
    example:
      amount: Deleniti esse repellat sunt delectus.
      date: Deserunt possimus qui excepturi ducimus.
      exchangeRate: Animi ut velit.
      identifier: Aut ad quas consequatur optio laboriosam.
    properties:
      amount:
        description: Amount of the transaction, EUR
        example: Deleniti esse repellat sunt delectus.
        type: string
      date:
        description: Date in RFC3339 format
        example: Deserunt possimus qui excepturi ducimus.
        type: string
      exchangeRate:
        description: Exchange rate
        example: Animi ut velit.
        type: string
      identifier:
        description: Payment reference
        example: Aut ad quas consequatur optio laboriosam.
        type: string
    required:
    - amount
    - identifier
    - exchangeRate
    title: 'Mediatype identifier: application/vnd.opendb.hack.transfer+json; view=default'
    type: object
  OpendbHackTransferCollection:
    description: OpendbHackTransferCollection is the media type for an array of OpendbHackTransfer
      (default view)
    example:
    - amount: Deleniti esse repellat sunt delectus.
      date: Deserunt possimus qui excepturi ducimus.
      exchangeRate: Animi ut velit.
      identifier: Aut ad quas consequatur optio laboriosam.
    items:
      $ref: '#/definitions/OpendbHackTransfer'
    title: 'Mediatype identifier: application/vnd.opendb.hack.transfer+json; type=collection'
    type: array
  PostBlockchainTransferBlockchainPayload:
    example:
      address: Sunt et quis aut.
      amount: Deleniti esse repellat sunt delectus.
      date: Deserunt possimus qui excepturi ducimus.
      exchangeRate: Animi ut velit.
      fee: Vel cumque in sint dignissimos ut.
      identifier: Aut ad quas consequatur optio laboriosam.
    properties:
      address:
        description: Blockchain address
        example: Sunt et quis aut.
        type: string
      amount:
        description: Amount of the transaction, EUR
        example: Deleniti esse repellat sunt delectus.
        type: string
      date:
        description: Date in RFC3339 format
        example: Deserunt possimus qui excepturi ducimus.
        type: string
      exchangeRate:
        description: Exchange rate
        example: Animi ut velit.
        type: string
      fee:
        description: Paid fee for transfer
        example: Vel cumque in sint dignissimos ut.
        type: string
      identifier:
        description: Payment reference
        example: Aut ad quas consequatur optio laboriosam.
        type: string
    required:
    - amount
    - address
    - identifier
    - exchangeRate
    title: PostBlockchainTransferBlockchainPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error'
    type: object
host: localhost:8881
info:
  version: ""
paths:
  /blockchain-transfers:
    get:
      operationId: blockchain#GetBlockchainTransfers
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/OpendbHackTransferCollection'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      security:
      - token: []
      summary: GetBlockchainTransfers blockchain
      tags:
      - blockchain
    post:
      operationId: blockchain#PostBlockchainTransfer
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PostBlockchainTransferBlockchainPayload'
      responses:
        "201":
          description: Created
          headers:
            ResourceId:
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      security:
      - token: []
      summary: PostBlockchainTransfer blockchain
      tags:
      - blockchain
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
securityDefinitions:
  token:
    in: header
    name: Authorisation
    type: apiKey
swagger: "2.0"
